// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhTJxVDhhkqj73ymYQwSjjHB0uAQRYYk',
    appId: '1:901958263034:web:f4517327f25c9f34182943',
    messagingSenderId: '901958263034',
    projectId: 'ecommerce-8f180',
    authDomain: 'ecommerce-8f180.firebaseapp.com',
    storageBucket: 'ecommerce-8f180.appspot.com',
    measurementId: 'G-TWMKESTCJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3UlACZms-av52RPlm4mXWUPb-ufkfXSo',
    appId: '1:901958263034:android:f1e97fb2faa41caf182943',
    messagingSenderId: '901958263034',
    projectId: 'ecommerce-8f180',
    storageBucket: 'ecommerce-8f180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaYJnoDhrnT9yxG1xDKABTEGoxBQDb3Uo',
    appId: '1:901958263034:ios:3a55af135388eb21182943',
    messagingSenderId: '901958263034',
    projectId: 'ecommerce-8f180',
    storageBucket: 'ecommerce-8f180.appspot.com',
    iosBundleId: 'com.example.newecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaYJnoDhrnT9yxG1xDKABTEGoxBQDb3Uo',
    appId: '1:901958263034:ios:3a55af135388eb21182943',
    messagingSenderId: '901958263034',
    projectId: 'ecommerce-8f180',
    storageBucket: 'ecommerce-8f180.appspot.com',
    iosBundleId: 'com.example.newecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlhTJxVDhhkqj73ymYQwSjjHB0uAQRYYk',
    appId: '1:901958263034:web:235664f73d63b3bc182943',
    messagingSenderId: '901958263034',
    projectId: 'ecommerce-8f180',
    authDomain: 'ecommerce-8f180.firebaseapp.com',
    storageBucket: 'ecommerce-8f180.appspot.com',
    measurementId: 'G-F699C13N7D',
  );
}
